# Project: YourTower
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = ../新增資料夾/Final/final.o main.o
LINKOBJ  = ../新增資料夾/Final/final.o main.o
LIBS     = -L"C:/Download/OSU!Songs/DevCppPortable/MinGW64/lib" -L"C:/Download/OSU!Songs/DevCppPortable/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Download/OSU!Songs/DevCppPortable/MinGW64/include" -I"C:/Download/OSU!Songs/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Download/OSU!Songs/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Download/OSU!Songs/DevCppPortable/MinGW64/include" -I"C:/Download/OSU!Songs/DevCppPortable/MinGW64/x86_64-w64-mingw32/include" -I"C:/Download/OSU!Songs/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Download/OSU!Songs/DevCppPortable/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = YourTower.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

../新增資料夾/Final/final.o: ../新增資料夾/Final/final.c
	$(CC) -c ../新增資料夾/Final/final.c -o ../新增資料夾/Final/final.o $(CFLAGS)

main.o: main.c
	$(CC) -c main.c -o main.o $(CFLAGS)
